import { ArrowLeft, Check, ChevronDown, FilePlus2, History, Pencil, Plus, ShieldCheck, Sparkles } from 'lucide-react';
import { useState, type FormEvent } from 'react';
import { Link, useParams } from 'wouter';
import { useQueryClient } from '@tanstack/react-query';
import { getGetPatientQueryKey, getListPatientReportsQueryKey, useAnalyzeReport, useCreatePatientReport, useGetPatient, useListPatientReports, useReviewReport, useUpdatePatient } from '@workspace/api-client-react';
import type { MedicalReport } from '@workspace/api-client-react';
import { ageFromDob, formatDate, formatDateTime, initials } from '@/lib/format';
import { Badge, Button, EmptyState, ErrorState, Field, Input, LoadingRows, SectionTitle, Textarea } from '@/components/ui';

export function PatientRecordPage() {
  const params = useParams<{ id: string }>();
  const id = Number(params.id);
  const patient = useGetPatient(id, { query: { queryKey: getGetPatientQueryKey(id), enabled: Number.isFinite(id) } });
  const reports = useListPatientReports(id, { query: { queryKey: getListPatientReportsQueryKey(id), enabled: Number.isFinite(id) } });
  const [showReportForm, setShowReportForm] = useState(false);
  const [selectedReport, setSelectedReport] = useState<number | null>(null);
  const queryClient = useQueryClient();
  const updatePatient = useUpdatePatient();
  const createReport = useCreatePatientReport();
  const analyzeReport = useAnalyzeReport();
  const reviewReport = useReviewReport();
  const [editOpen, setEditOpen] = useState(false);
  const p = patient.data;
  const reportList = reports.data ?? p?.reports ?? [];
  const selected = reportList.find((report) => report.id === selectedReport) ?? reportList[0];
  const [note, setNote] = useState('');
  const [reportForm, setReportForm] = useState({ title: '', reportDate: '', sourceText: '' });
  const [editForm, setEditForm] = useState({ symptoms: '', conditions: '', allergies: '', medications: '' });
  const openEdit = () => { if (!p) return; setEditForm({ symptoms: p.symptoms, conditions: p.conditions.join(', '), allergies: p.allergies.join(', '), medications: p.medications.join(', ') }); setEditOpen(true); };
  const saveEdit = (event: FormEvent) => { event.preventDefault(); if (!p) return; updatePatient.mutate({ id, data: { name: p.name, dateOfBirth: p.dateOfBirth, sex: p.sex, symptoms: editForm.symptoms, conditions: splitList(editForm.conditions), allergies: splitList(editForm.allergies), medications: splitList(editForm.medications) } }, { onSuccess: () => { queryClient.invalidateQueries({ queryKey: getGetPatientQueryKey(id) }); setEditOpen(false); } }); };
  const submitReport = (event: FormEvent) => { event.preventDefault(); if (!reportForm.title || !reportForm.reportDate || !reportForm.sourceText) return; createReport.mutate({ id, data: reportForm }, { onSuccess: () => { queryClient.invalidateQueries({ queryKey: getListPatientReportsQueryKey(id) }); queryClient.invalidateQueries({ queryKey: getGetPatientQueryKey(id) }); setReportForm({ title: '', reportDate: '', sourceText: '' }); setShowReportForm(false); } }); };
  const analyze = (reportId: number) => analyzeReport.mutate({ id: reportId }, { onSuccess: () => { queryClient.invalidateQueries({ queryKey: getListPatientReportsQueryKey(id) }); } });
  const verify = (report: MedicalReport) => reviewReport.mutate({ id: report.id, data: { reviewStatus: 'verified', summary: report.summary, extractedTests: report.extractedTests } }, { onSuccess: () => { queryClient.invalidateQueries({ queryKey: getListPatientReportsQueryKey(id) }); } });
  if (patient.isLoading) return <div className="mx-auto max-w-[1500px] px-5 py-10 sm:px-8 lg:px-12"><LoadingRows count={5} /></div>;
  if (patient.isError || !p) return <div className="mx-auto max-w-[900px] px-5 py-10"><ErrorState detail="This patient record could not be found or loaded." /></div>;
  return <div className="mx-auto max-w-[1500px] px-5 py-7 sm:px-8 lg:px-12 lg:py-10">
    <Link href="/patients" className="mb-8 inline-flex items-center gap-2 text-sm font-bold text-muted-foreground transition hover:text-primary" data-testid="link-record-back"><ArrowLeft size={15} /> Patient index</Link>
    <header className="mb-8 flex flex-col justify-between gap-5 xl:flex-row xl:items-end"><div className="flex items-start gap-4"><div className="grid h-14 w-14 shrink-0 place-items-center rounded-2xl bg-secondary font-serif text-xl text-primary">{initials(p.name)}</div><div><div className="mb-2 font-mono text-[10px] uppercase tracking-[.2em] text-primary">Patient record · #{String(p.id).padStart(4, '0')}</div><h1 className="font-serif text-4xl tracking-[-.045em] sm:text-5xl">{p.name}</h1><p className="mt-2 text-sm text-muted-foreground">{ageFromDob(p.dateOfBirth)} years · {p.sex} · Last updated {formatDate(p.updatedAt)}</p></div></div><div className="flex gap-2"><Button variant="outline" onClick={openEdit} data-testid="button-edit-patient"><Pencil size={15} /> Edit context</Button><Button onClick={() => setShowReportForm(!showReportForm)} data-testid="button-add-report"><FilePlus2 size={15} /> Add report</Button></div></header>
    <div className="grid gap-8 xl:grid-cols-[minmax(0,1.1fr)_380px]">
      <div className="space-y-8">
        {showReportForm && <form onSubmit={submitReport} className="animate-rise-in rounded-xl border border-primary/25 bg-primary/[.045] p-5 sm:p-7"><div className="mb-5 flex items-center justify-between"><div><div className="font-mono text-[10px] uppercase tracking-[.18em] text-primary">New source document</div><h2 className="mt-1 font-serif text-2xl font-semibold">Add a report to review</h2></div><button type="button" onClick={() => setShowReportForm(false)} className="text-sm text-muted-foreground" data-testid="button-close-report-form">Close</button></div><div className="grid gap-5 sm:grid-cols-2"><Field label="Report title"><Input value={reportForm.title} onChange={(e) => setReportForm({ ...reportForm, title: e.target.value })} placeholder="e.g. Complete blood count" data-testid="input-report-title" /></Field><Field label="Report date"><Input type="date" value={reportForm.reportDate} onChange={(e) => setReportForm({ ...reportForm, reportDate: e.target.value })} data-testid="input-report-date" /></Field></div><Field label="Source text" hint="Paste the report text as provided. MedLens will preserve it as the source of truth."><Textarea value={reportForm.sourceText} onChange={(e) => setReportForm({ ...reportForm, sourceText: e.target.value })} className="mt-1" placeholder="Paste report text here…" data-testid="textarea-report-source" /></Field><div className="mt-4 flex justify-end"><Button type="submit" loading={createReport.isPending} data-testid="button-submit-report"><Plus size={15} /> Add report</Button></div></form>}
        <section><SectionTitle eyebrow="Source documents" title="Reports & extracted evidence" detail="Review the source before relying on any extracted observation." /><div className="space-y-3">{reports.isLoading ? <LoadingRows count={3} /> : reports.isError ? <ErrorState onRetry={() => reports.refetch()} /> : reportList.length ? reportList.map((report) => <ReportCard key={report.id} report={report} selected={selected?.id === report.id} onSelect={() => setSelectedReport(report.id)} onAnalyze={() => analyze(report.id)} onVerify={() => verify(report)} analyzing={analyzeReport.isPending} verifying={reviewReport.isPending} />) : <EmptyState title="No reports attached" detail="Add a source document to give this patient record more context." action={<Button onClick={() => setShowReportForm(true)} data-testid="button-empty-add-report"><FilePlus2 size={15} /> Add first report</Button>} />}</div></section>
        {selected && <ReportDetail report={selected} note={note} setNote={setNote} />}
      </div>
      <aside className="space-y-5"><section className="rounded-xl border border-card-border bg-card p-5"><SectionTitle eyebrow="Patient context" title="At a glance" /><div className="space-y-5"><ContextRow label="Symptoms" value={p.symptoms || 'No symptoms recorded'} /><ContextRow label="Conditions" value={p.conditions.length ? p.conditions.join(', ') : 'None recorded'} /><ContextRow label="Allergies" value={p.allergies.length ? p.allergies.join(', ') : 'None recorded'} alert={p.allergies.length > 0} /><ContextRow label="Medications" value={p.medications.length ? p.medications.join(', ') : 'None recorded'} /></div></section><section className="rounded-xl border border-card-border bg-sidebar p-5 text-sidebar-foreground"><div className="flex items-center gap-2 text-sidebar-primary"><ShieldCheck size={17} /><span className="font-mono text-[10px] font-medium uppercase tracking-[.16em]">Traceability</span></div><p className="mt-4 text-sm leading-6 text-sidebar-foreground/70">Every extracted item links back to its report source and review status. A human review is always the final step.</p><div className="mt-5 flex items-center gap-2 text-xs font-semibold"><History size={14} /> {p.reportCount} source record{p.reportCount === 1 ? '' : 's'} on file</div></section></aside>
    </div>
    {editOpen && <div className="fixed inset-0 z-50 grid place-items-center bg-foreground/30 p-4 backdrop-blur-[2px]" role="dialog" aria-modal="true"><form onSubmit={saveEdit} className="w-full max-w-2xl rounded-2xl border border-card-border bg-card p-6 shadow-2xl sm:p-8"><div className="mb-6 flex items-start justify-between"><div><div className="font-mono text-[10px] uppercase tracking-[.18em] text-primary">Edit patient context</div><h2 className="mt-1 font-serif text-2xl font-semibold">{p.name}</h2></div><button type="button" onClick={() => setEditOpen(false)} className="text-sm text-muted-foreground" data-testid="button-close-edit">Close</button></div><div className="space-y-4"><Field label="Symptoms"><Textarea value={editForm.symptoms} onChange={(e) => setEditForm({ ...editForm, symptoms: e.target.value })} data-testid="textarea-edit-symptoms" /></Field><Field label="Known conditions"><Input value={editForm.conditions} onChange={(e) => setEditForm({ ...editForm, conditions: e.target.value })} data-testid="input-edit-conditions" /></Field><div className="grid gap-4 sm:grid-cols-2"><Field label="Allergies"><Input value={editForm.allergies} onChange={(e) => setEditForm({ ...editForm, allergies: e.target.value })} data-testid="input-edit-allergies" /></Field><Field label="Medications"><Input value={editForm.medications} onChange={(e) => setEditForm({ ...editForm, medications: e.target.value })} data-testid="input-edit-medications" /></Field></div></div><div className="mt-6 flex justify-end gap-2"><Button type="button" variant="quiet" onClick={() => setEditOpen(false)} data-testid="button-cancel-edit">Cancel</Button><Button type="submit" loading={updatePatient.isPending} data-testid="button-save-edit"><Check size={15} /> Save context</Button></div></form></div>}
  </div>;
}

function ContextRow({ label, value, alert }: { label: string; value: string; alert?: boolean }) { return <div><div className="font-mono text-[10px] uppercase tracking-[.12em] text-muted-foreground">{label}</div><p className={`mt-1.5 text-sm leading-6 ${alert ? 'text-destructive' : ''}`}>{value}</p></div>; }

function ReportCard({ report, selected, onSelect, onAnalyze, onVerify, analyzing, verifying }: { report: MedicalReport; selected: boolean; onSelect: () => void; onAnalyze: () => void; onVerify: () => void; analyzing: boolean; verifying: boolean }) {
  return <div className={`rounded-xl border bg-card transition ${selected ? 'border-primary/45 shadow-[0_8px_25px_rgba(25,103,99,.07)]' : 'border-card-border'}`} data-testid={`card-report-${report.id}`}><button onClick={onSelect} className="flex w-full items-center gap-4 p-4 text-left sm:p-5" data-testid={`button-expand-report-${report.id}`}><div className="grid h-10 w-10 shrink-0 place-items-center rounded-lg bg-secondary text-primary"><FilePlus2 size={17} /></div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h3 className="truncate font-semibold">{report.title}</h3><Badge tone={report.reviewStatus === 'verified' ? 'teal' : report.reviewStatus === 'processing' ? 'blue' : 'amber'}>{report.reviewStatus.replace('_', ' ')}</Badge></div><p className="mt-1 text-xs text-muted-foreground">{formatDate(report.reportDate)} · Added {formatDate(report.createdAt)}</p></div><ChevronDown size={17} className={`shrink-0 text-muted-foreground transition ${selected ? 'rotate-180' : ''}`} /></button>{selected && <div className="border-t border-border px-4 pb-5 pt-4 sm:px-5"><p className="line-clamp-3 text-sm leading-6 text-muted-foreground">{report.summary || 'No summary has been generated yet.'}</p><div className="mt-4 flex flex-wrap gap-2">{report.reviewStatus === 'needs_review' && <Button variant="outline" onClick={onAnalyze} loading={analyzing} data-testid={`button-analyze-report-${report.id}`}><Sparkles size={14} /> Extract evidence</Button>}{report.reviewStatus !== 'verified' && <Button onClick={onVerify} loading={verifying} data-testid={`button-verify-report-${report.id}`}><Check size={14} /> Mark reviewed</Button>}</div></div>}</div>;
}

function ReportDetail({ report, note, setNote }: { report: MedicalReport; note: string; setNote: (value: string) => void }) {
  const tests = report.extractedTests ?? [];
  return <section className="animate-rise-in rounded-xl border border-card-border bg-card"><div className="border-b border-border p-5 sm:p-7"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="mb-2 font-mono text-[10px] uppercase tracking-[.16em] text-primary">Evidence view · report #{report.id}</div><h2 className="font-serif text-2xl font-semibold tracking-[-.025em]">{report.title}</h2></div><Badge tone={report.reviewStatus === 'verified' ? 'teal' : 'amber'}>{report.reviewStatus.replace('_', ' ')}</Badge></div><p className="mt-4 max-w-3xl text-sm leading-7">{report.summary || 'No extracted summary yet. Run extraction after reviewing the source text.'}</p></div><div className="p-5 sm:p-7">{tests.length > 0 && <div><div className="mb-3 flex items-center justify-between"><h3 className="text-sm font-bold">Extracted observations</h3><span className="font-mono text-[10px] uppercase tracking-[.1em] text-muted-foreground">Provenance visible</span></div><div className="overflow-x-auto rounded-lg border border-border"><table className="w-full min-w-[620px] text-left text-sm"><thead className="bg-muted/60 text-[10px] uppercase tracking-[.1em] text-muted-foreground"><tr><th className="px-3 py-3 font-medium">Test</th><th className="px-3 py-3 font-medium">Value</th><th className="px-3 py-3 font-medium">Reference</th><th className="px-3 py-3 font-medium">Status</th><th className="px-3 py-3 font-medium">Source</th></tr></thead><tbody>{tests.map((test, index) => <tr key={`${test.name}-${index}`} className="border-t border-border"><td className="px-3 py-3 font-semibold">{test.name}</td><td className="px-3 py-3">{test.value} {test.unit}</td><td className="px-3 py-3 text-muted-foreground">{test.referenceRange}</td><td className="px-3 py-3"><Badge tone={test.status === 'normal' ? 'teal' : test.status === 'unknown' ? 'neutral' : 'amber'}>{test.status}</Badge></td><td className="px-3 py-3 text-xs text-muted-foreground">{test.provenance.replace('_', ' ')}</td></tr>)}</tbody></table></div></div>}<div className="mt-7 grid gap-5 lg:grid-cols-2"><div><h3 className="mb-3 text-sm font-bold">Source text</h3><pre className="max-h-72 overflow-auto whitespace-pre-wrap rounded-lg bg-muted/55 p-4 font-mono text-xs leading-6 text-muted-foreground scrollbar-thin">{report.sourceText}</pre></div><div><h3 className="mb-3 text-sm font-bold">Reviewer note</h3><Textarea value={note} onChange={(e) => setNote(e.target.value)} placeholder="Add a local note for your team…" className="min-h-32" data-testid={`textarea-reviewer-note-${report.id}`} /><p className="mt-2 text-[11px] leading-5 text-muted-foreground">Notes stay in this view and are not used as clinical recommendations.</p></div></div></div></section>;
}

const splitList = (value: string) => value.split(',').map((item) => item.trim()).filter(Boolean);
