import { Link } from 'wouter';
import { Search, Plus, ArrowUpRight, Filter } from 'lucide-react';
import { useState } from 'react';
import { useListPatients } from '@workspace/api-client-react';
import { formatDate, initials } from '@/lib/format';
import { Badge, EmptyState, ErrorState, Input, LoadingRows, SectionTitle } from '@/components/ui';

export function PatientsPage() {
  const [search, setSearch] = useState('');
  const [status, setStatus] = useState<'all' | 'needs_review' | 'review_ready'>('all');
  const patients = useListPatients({ search: search || undefined, status: status === 'all' ? undefined : status });
  const data = patients.data ?? [];
  return <div className="mx-auto max-w-[1500px] px-5 py-7 sm:px-8 lg:px-12 lg:py-10">
    <header className="mb-8 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><div className="mb-3 font-mono text-[10px] uppercase tracking-[.2em] text-primary">Patient index</div><h1 className="font-serif text-4xl tracking-[-.045em] sm:text-5xl">The whole record,<br /><em className="text-primary">in context.</em></h1><p className="mt-3 text-sm text-muted-foreground">Search and open a traceable patient workspace.</p></div><Link href="/patients/new" className="inline-flex min-h-11 items-center justify-center gap-2 rounded-lg bg-primary px-4 text-sm font-bold text-primary-foreground" data-testid="link-patients-add"><Plus size={16} /> Add patient</Link></header>
    <section className="rounded-xl border border-card-border bg-card p-3 shadow-[0_8px_30px_rgba(37,58,55,.04)] sm:p-4">
      <div className="flex flex-col gap-3 lg:flex-row"><label className="relative flex-1"><Search size={17} className="absolute left-3.5 top-3.5 text-muted-foreground" /><Input type="search" value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search by patient name or symptom…" className="pl-10" data-testid="input-patient-search" /></label><div className="flex gap-2 overflow-auto"><Filter size={17} className="ml-2 mt-3 shrink-0 text-muted-foreground" />{([['all', 'All patients'], ['needs_review', 'Needs review'], ['review_ready', 'Review ready']] as const).map(([value, label]) => <button key={value} onClick={() => setStatus(value)} className={`whitespace-nowrap rounded-lg px-3 py-2 text-xs font-bold transition ${status === value ? 'bg-primary text-primary-foreground' : 'bg-muted text-muted-foreground hover:bg-secondary'}`} data-testid={`button-filter-${value}`}>{label}</button>)}</div></div>
    </section>
    <div className="mt-8"><SectionTitle eyebrow={`${data.length} record${data.length === 1 ? '' : 's'}`} title="Patient records" detail="Most recently updated appears first." /></div>
    {patients.isLoading ? <LoadingRows count={5} /> : patients.isError ? <ErrorState onRetry={() => patients.refetch()} /> : data.length ? <div className="grid gap-3 xl:grid-cols-2">{data.map((patient) => <Link href={`/patients/${patient.id}`} key={patient.id} className="card-lift group rounded-xl border border-card-border bg-card p-5" data-testid={`card-patient-${patient.id}`}><div className="flex items-start justify-between gap-4"><div className="flex min-w-0 items-center gap-3.5"><div className="grid h-11 w-11 shrink-0 place-items-center rounded-xl bg-secondary font-serif text-lg text-primary">{initials(patient.name)}</div><div className="min-w-0"><h3 className="truncate font-serif text-xl font-semibold tracking-[-.025em]">{patient.name}</h3><p className="mt-1 text-xs text-muted-foreground">{patient.sex} · Born {formatDate(patient.dateOfBirth)}</p></div></div><ArrowUpRight size={17} className="text-muted-foreground transition group-hover:text-primary" /></div><div className="mt-5 grid grid-cols-3 gap-3 border-t border-border pt-4"><div><div className="font-mono text-[9px] uppercase tracking-[.1em] text-muted-foreground">Reports</div><div className="mt-1 text-sm font-bold">{patient.reportCount}</div></div><div><div className="font-mono text-[9px] uppercase tracking-[.1em] text-muted-foreground">Updated</div><div className="mt-1 text-sm font-bold">{formatDate(patient.updatedAt)}</div></div><div><div className="font-mono text-[9px] uppercase tracking-[.1em] text-muted-foreground">Status</div><div className="mt-1">{patient.needsReview ? <Badge tone="amber">Review</Badge> : <Badge tone="teal">Ready</Badge>}</div></div></div></Link>)}</div> : <EmptyState title={search ? 'No records match that search' : 'No patient records yet'} detail={search ? 'Try a different name or symptom, or clear the search.' : 'Add a patient to begin building a careful, traceable record.'} action={!search ? <Link href="/patients/new" className="inline-flex min-h-10 items-center gap-2 rounded-lg bg-primary px-4 text-sm font-bold text-primary-foreground" data-testid="link-empty-patients-add"><Plus size={15} /> Add patient</Link> : undefined} />}
  </div>;
}
