import { Check, LockKeyhole, ShieldCheck, SlidersHorizontal } from 'lucide-react';
import { useState } from 'react';
import { Button, Badge, SectionTitle } from '@/components/ui';

export function SettingsPage() {
  const [saved, setSaved] = useState(false);
  const [preferences, setPreferences] = useState({ autoExtract: true, showSource: true, reviewPrompts: true });
  const toggle = (key: keyof typeof preferences) => { setPreferences((old) => ({ ...old, [key]: !old[key] })); setSaved(false); };
  return <div className="mx-auto max-w-[1050px] px-5 py-7 sm:px-8 lg:px-12 lg:py-10">
    <div className="mb-10"><div className="mb-3 font-mono text-[10px] uppercase tracking-[.2em] text-primary">Workspace controls</div><h1 className="font-serif text-4xl tracking-[-.045em] sm:text-5xl">Keep the signal<br /><em className="text-primary">carefully bounded.</em></h1><p className="mt-3 max-w-xl text-sm leading-6 text-muted-foreground">Settings for how MedLens organizes evidence and brings human review into focus.</p></div>
    <div className="space-y-8">
      <section><SectionTitle eyebrow="Safety by default" title="Review behavior" detail="These controls shape your team’s workflow, not clinical decisions." /><div className="overflow-hidden rounded-xl border border-card-border bg-card">{[['autoExtract', 'Extract observations after a report is added', 'Use assisted extraction to organize possible tests and observations.'], ['showSource', 'Keep source text visible beside extracted data', 'Maintain a direct line back to the original report.'], ['reviewPrompts', 'Prompt for human review before verification', 'Never treat extracted information as verified automatically.']].map(([key, title, detail]) => <div key={key} className="flex items-start justify-between gap-5 border-b border-border p-5 last:border-b-0 sm:p-6"><div><h3 className="text-sm font-bold">{title}</h3><p className="mt-1 max-w-2xl text-xs leading-5 text-muted-foreground">{detail}</p></div><button role="switch" aria-checked={preferences[key as keyof typeof preferences]} onClick={() => toggle(key as keyof typeof preferences)} className={`relative h-6 w-11 shrink-0 rounded-full p-1 transition ${preferences[key as keyof typeof preferences] ? 'bg-primary' : 'bg-muted'}`} data-testid={`switch-${key}`}><span className={`block h-4 w-4 rounded-full bg-card shadow-sm transition-transform ${preferences[key as keyof typeof preferences] ? 'translate-x-5' : ''}`} /></button></div>)}</div></section>
      <section><SectionTitle eyebrow="Data handling" title="Workspace boundary" /><div className="grid gap-4 sm:grid-cols-2"><div className="rounded-xl border border-card-border bg-card p-5"><LockKeyhole size={19} className="text-primary" /><h3 className="mt-5 font-serif text-xl font-semibold">Evidence stays traceable</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">Source reports are preserved alongside extracted observations and their provenance. Nothing is silently rewritten.</p><Badge tone="teal">Source-first</Badge></div><div className="rounded-xl border border-card-border bg-card p-5"><ShieldCheck size={19} className="text-primary" /><h3 className="mt-5 font-serif text-xl font-semibold">Human review is the gate</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">Only a reviewer can mark report information verified. MedLens does not diagnose, prescribe, or make treatment recommendations.</p><Badge tone="amber">Review required</Badge></div></div></section>
      <div className="flex items-center justify-between border-t border-border pt-5"><div className="flex items-center gap-2 text-xs text-muted-foreground"><SlidersHorizontal size={14} /> Preferences are local to this workspace.</div><Button onClick={() => { setSaved(true); setTimeout(() => setSaved(false), 2600); }} data-testid="button-save-settings">{saved ? <><Check size={15} /> Saved</> : 'Save preferences'}</Button></div>
    </div>
  </div>;
}
